### ISSUE TITLE
Development branch is broken

### ISSUE THREAD

**Issue by akseli-kolari** [finnishtransportagency/suomen-vaylat#257]
Hi!

This might be intentional, but the application has been broken for us mere mortals after you merged [branch 'development' of codecommit://suomen-vaylat into development](https://github.com/finnishtransportagency/suomen-vaylat/commit/ccdee8b35bc32739288a7ead7fbdd78b51c8e04a).

For example, when you open the app it will immediately say "channel.getAllLayersSV is not a function" and if you try to open the "info box" about a road the app will crash with "title.toUpperCase is not a function".

Reverting the commit fixes all the issues though.

**Comment by osqq** [comment]
Very very very late reply but this repository got changed to only be used as a way to share the code for public use/viewing and the actual development repository is now (and has been for a while) elsewhere. This is why we got rid of the other branches and only update the newest releases here.
